
int t = 0;
int delayTime = delayTime;
int potPin = A0;

void setup()
{
  for(int x = 2 ; x<=12 ; x++){
  pinMode(x,OUTPUT);}
  pinMode (2 , OUTPUT);
  pinMode (3 , OUTPUT);
  pinMode (4 , OUTPUT);
  pinMode (5 , OUTPUT);
  pinMode (6 , OUTPUT);
  pinMode (7 , OUTPUT);
  pinMode (8 , OUTPUT);
  pinMode (9 , OUTPUT);
  pinMode (10 , OUTPUT);
  pinMode (11, OUTPUT);
  pinMode (12 , OUTPUT);
  pinMode(13, INPUT);
}

void loop()
{
  if (digitalRead(13)==HIGH){
    t++;
	delayTime = analogRead(potPin);
    delay(delayTime);}
    
if (t==1){
  pattern1();}
if (t==2){
  pattern2();}
if (t==3){
  pattern3();}
if (t==4){
  pattern4();}
if (t==5){
  pattern5();}
if (t==6){
  pattern6();}
if (t==7){
  pattern7();}
if (t==8){
  pattern8();}
if (t==9){
  pattern9();}
if (t==10){
  pattern10();}
if (t==11){
  pattern11();}
if (t==12){
  pattern12();}
if (t==13){
  pattern13();}
if (t==14){
  pattern14();}
if (t==15){
  pattern15();}
if (t==16){
  pattern16();}
if (t==17){
  pattern17();}}
  
void pattern1(){
  for(int x = 2; x<=12 ; x++){
  	delayTime = analogRead(potPin);
    digitalWrite(x, HIGH);
    delay(delayTime);
    digitalWrite(x, LOW);
    delay(delayTime);}}
    
void pattern2(){    
  for(int x = 2; x<=12 ; x++){
  	delayTime = analogRead(potPin);
    digitalWrite(x, HIGH);
    delay(delayTime);
    digitalWrite(x, LOW);}
  for(int x = 12; x>=2 ; x--){
  	delayTime = analogRead(potPin);
    digitalWrite(x, HIGH);
    delay(delayTime);
    digitalWrite(x, LOW);}}
    
void pattern3(){
  for(int x = 2; x<=13 ; x=x+2){
  	delayTime = analogRead(potPin);
    digitalWrite(x, HIGH);
    delay(delayTime);
    digitalWrite(x, LOW);
    delay(delayTime);}
  for(int x = 12; x>=2 ; x=x-2){
  	delayTime = analogRead(potPin);
    digitalWrite(x, HIGH);
    delay(delayTime);
    digitalWrite(x, LOW);
    delay(delayTime);}}
    
void pattern4(){
  delayTime = analogRead(potPin);
  digitalWrite(2, HIGH);
  digitalWrite(12, HIGH);
  delay(delayTime);
  digitalWrite(2, LOW);
  digitalWrite(12, LOW);
  delay(delayTime);
  digitalWrite(3, HIGH);
  digitalWrite(11, HIGH);
  delay(delayTime);
  digitalWrite(3, LOW);
  digitalWrite(11, LOW);
  delay(delayTime);
  digitalWrite(4, HIGH);
  digitalWrite(10, HIGH);
  delay(delayTime);
  digitalWrite(4, LOW);
  digitalWrite(10, LOW);
  delay(delayTime);
  digitalWrite(5, HIGH);
  digitalWrite(9, HIGH);
  delay(delayTime);
  digitalWrite(5, LOW);
  digitalWrite(9, LOW);
  delay(delayTime);
  digitalWrite(6, HIGH);
  digitalWrite(8, HIGH);
  delay(delayTime);
  digitalWrite(6, LOW);
  digitalWrite(8, LOW);
  delay(delayTime);
  digitalWrite(7, HIGH);
  delay(delayTime);
  digitalWrite(7, LOW);
  delay(delayTime);
  digitalWrite(6, HIGH);
  digitalWrite(8, HIGH);
  delay(delayTime);
  digitalWrite(6, LOW);
  digitalWrite(8, LOW);
  delay(delayTime);
  digitalWrite(5, HIGH);
  digitalWrite(9, HIGH);
  delay(delayTime);
  digitalWrite(5, LOW);
  digitalWrite(9, LOW);
  delay(delayTime);
  digitalWrite(4, HIGH);
  digitalWrite(10, HIGH);
  delay(delayTime);
  digitalWrite(4, LOW);
  digitalWrite(10, LOW);
  delay(delayTime);
  digitalWrite(3, HIGH);
  digitalWrite(11, HIGH);
  delay(delayTime);
  digitalWrite(3, LOW);
  digitalWrite(11, LOW);
  delay(delayTime);
  digitalWrite(2, HIGH);
  digitalWrite(12, HIGH);
  delay(delayTime);
  digitalWrite(2, LOW);
  digitalWrite(12, LOW);
  delay(delayTime);}
  
void pattern5(){
  for(int x = 2; x<=12 ; x++){
	delayTime = analogRead(potPin);
    digitalWrite(x, HIGH);
    delay(delayTime);}
  for(int x = 2; x<=12 ; x++){
	delayTime = analogRead(potPin);
    digitalWrite(x, LOW);
    delay(delayTime);}}
    
void pattern6(){
  for(int x = 2; x<=12 ; x++){
	delayTime = analogRead(potPin);
    digitalWrite(x, HIGH);
    delay(delayTime);}
  for(int x =12 ; x>=2 ; x--){
	delayTime = analogRead(potPin);
    digitalWrite(x, LOW);
    delay(delayTime);}}
    
void pattern7(){
  delayTime = analogRead(potPin);
  digitalWrite ( 2, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 3, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 4, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 4, LOW);
  digitalWrite ( 5, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 5, LOW);
  digitalWrite ( 6, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 5, HIGH);
  digitalWrite ( 6, LOW);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 5, HIGH);
  digitalWrite ( 6, HIGH);
  digitalWrite ( 7, LOW);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 6, HIGH);
  digitalWrite ( 7, HIGH);
  digitalWrite ( 8, LOW);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 7, HIGH);
  digitalWrite ( 8, HIGH);
  digitalWrite ( 9, LOW);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  digitalWrite ( 8, HIGH);
  digitalWrite ( 9, HIGH);
  digitalWrite ( 10, LOW);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 8, LOW);
  digitalWrite ( 9, HIGH);
  digitalWrite ( 10, HIGH);
  digitalWrite ( 11, LOW);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 9, LOW);
  digitalWrite ( 10, HIGH);
  digitalWrite ( 11, HIGH);
  digitalWrite ( 12, LOW);
  delay (delayTime);
  digitalWrite ( 10, LOW);
  digitalWrite ( 11, HIGH);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 11, LOW);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 12, LOW);
  delay (delayTime);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 12, HIGH);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 10, HIGH);
  digitalWrite ( 11, HIGH);
  digitalWrite ( 12, LOW);
  delay (00);
  digitalWrite ( 12, HIGH);
  digitalWrite ( 10, HIGH);
  digitalWrite ( 9, HIGH);
  digitalWrite ( 11, LOW);
  delay (delayTime);
  digitalWrite ( 11, HIGH);
  digitalWrite ( 8, HIGH);
  digitalWrite ( 9, HIGH);
  digitalWrite ( 10, LOW);
  delay (delayTime);
  digitalWrite ( 7, HIGH);
  digitalWrite ( 10, HIGH);
  digitalWrite ( 8, HIGH);
  digitalWrite ( 9, LOW);
  delay (delayTime);
  digitalWrite ( 6, HIGH);
  digitalWrite ( 7, HIGH);
  digitalWrite ( 9, HIGH);
  digitalWrite ( 8, LOW);
  delay (delayTime);
  digitalWrite ( 5, HIGH);
  digitalWrite ( 6, HIGH);
  digitalWrite ( 8, HIGH);
  digitalWrite ( 7, LOW);
  delay (delayTime);
  digitalWrite ( 5, HIGH);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 7, HIGH);
  digitalWrite ( 6, LOW);
  delay (delayTime);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 6, HIGH);
  digitalWrite ( 5, LOW);
  delay (delayTime);
  digitalWrite ( 5, HIGH);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 2, HIGH);
  digitalWrite ( 4, LOW);
  delay (delayTime);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 2, HIGH);
  digitalWrite ( 3, LOW);
  delay (delayTime);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 2, LOW);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  delay (delayTime);
  digitalWrite ( 12, LOW);
  delay (delayTime);
  digitalWrite ( 11, LOW);
  delay (delayTime);
  digitalWrite ( 10, LOW);
  delay (delayTime);
  digitalWrite ( 9, LOW);
  delay (delayTime);
  digitalWrite ( 8, LOW);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  delay (delayTime);}

void pattern8(){
  delayTime = analogRead(potPin);
  digitalWrite ( 2, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  digitalWrite ( 3, HIGH);
  delay (delayTime);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 4, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 5, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 5, HIGH);
  digitalWrite ( 6, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 5, HIGH);
  digitalWrite ( 6, HIGH);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 6, HIGH);
  digitalWrite ( 7, HIGH);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 7, HIGH);
  digitalWrite ( 8, HIGH);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  digitalWrite ( 8, HIGH);
  digitalWrite ( 9, HIGH);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 8, LOW);
  digitalWrite ( 9, HIGH);
  digitalWrite ( 10, HIGH);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 9, LOW);
  digitalWrite ( 10, HIGH);
  digitalWrite ( 11, HIGH);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 10, LOW);
  digitalWrite ( 11, HIGH);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 11, LOW);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 12, LOW);
  delay (delayTime);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 12, LOW);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 11, LOW);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 10, LOW);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 9, LOW);
  digitalWrite ( 6, HIGH);
  delay (delayTime);
  digitalWrite ( 8, LOW);
  digitalWrite ( 5, HIGH);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  digitalWrite ( 4, HIGH);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 3, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 2, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  delay (delayTime);}
  
void pattern9(){  
  delayTime = analogRead(potPin);
  digitalWrite ( 2, HIGH);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 12, LOW);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 11, LOW);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 10, LOW);
  digitalWrite ( 5, HIGH);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 9, LOW);
  digitalWrite ( 6, HIGH);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 8, LOW);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  delay (delayTime);}

void pattern10(){ 
  delayTime = analogRead(potPin);
  digitalWrite ( 2, HIGH);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 12, LOW);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 11, LOW);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 10, LOW);
  digitalWrite ( 5, HIGH);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 9, LOW);
  digitalWrite ( 6, HIGH);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 8, LOW);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 6, HIGH);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 5, HIGH);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 8, LOW);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 9, LOW);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 10, LOW);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 11, LOW);
  delay(delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 12, LOW);
  delay(delayTime);}
  
void pattern11(){
  delayTime = analogRead(potPin);
  digitalWrite ( 2, HIGH);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 5, HIGH);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 8, HIGH);
  digitalWrite ( 6, HIGH);
  delay (delayTime);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 12, LOW);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 11, LOW);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 10, LOW);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 9, LOW);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 8, LOW);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  delay (delayTime);}
  
void pattern12(){
  delayTime = analogRead(potPin);
  digitalWrite ( 2, HIGH);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 5, HIGH);
  digitalWrite ( 6, HIGH);
  digitalWrite ( 7, HIGH);
  digitalWrite ( 8, HIGH);
  digitalWrite ( 9, HIGH);
  digitalWrite ( 10, HIGH);
  digitalWrite ( 11, HIGH);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 12, LOW);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 11, LOW);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 10, LOW);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 9, LOW);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 8, LOW);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 5, HIGH);
  digitalWrite ( 6, HIGH);
  digitalWrite ( 7, HIGH);
  digitalWrite ( 8, HIGH);
  digitalWrite ( 9, HIGH);
  digitalWrite ( 10, HIGH);
  digitalWrite ( 11, HIGH);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 8, LOW);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 9, LOW);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 10, LOW);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 11, LOW);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 12, LOW);
  delay (delayTime);}
  
void pattern13(){
  delayTime = analogRead(potPin);
  digitalWrite ( 2, HIGH);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 12, LOW);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 11, LOW);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 10, LOW);
  digitalWrite ( 5, HIGH);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 9, LOW);
  digitalWrite ( 6, HIGH);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 8, LOW);
  delay (delayTime);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 12, LOW);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 11, LOW);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 10, LOW);
  digitalWrite ( 5, HIGH);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 9, LOW);
  digitalWrite ( 6, HIGH);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 12, LOW);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 11, LOW);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 10, LOW);
  digitalWrite ( 5, HIGH);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 12, LOW);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 11, LOW);
  digitalWrite ( 4, HIGH);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 12, LOW);
  digitalWrite ( 3, HIGH);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 3, LOW);
  digitalWrite ( 4, LOW);
  digitalWrite ( 5, LOW);
  digitalWrite ( 6, LOW);
  digitalWrite ( 7, LOW);
  digitalWrite ( 8, LOW);
  digitalWrite ( 9, LOW);
  digitalWrite ( 10, LOW);
  digitalWrite ( 11, LOW);
  digitalWrite ( 12, LOW);
  delay (delayTime);}
  
void pattern14(){
  delayTime = analogRead(potPin);
  digitalWrite ( 2, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 3, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 4, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 5, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 6, HIGH);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 8, LOW);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 9, LOW);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 10, LOW);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 11, LOW);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 3, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 4, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 5, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 6, HIGH);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 8, LOW);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 9, LOW);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 10, LOW);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 3, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 4, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 5, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 6, HIGH);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 8, LOW);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 9, LOW);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 3, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 4, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 5, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 6, HIGH);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 8, LOW);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 3, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 4, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 5, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 6, HIGH);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 3, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 4, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 5, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 6, HIGH);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 3, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 4, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 5, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 6, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 3, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 4, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 5, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 3, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 4, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 3, HIGH);
  delay (delayTime);
  digitalWrite ( 2, HIGH);
  delay (delayTime);}

void pattern15(){
  delayTime = analogRead(potPin);
  digitalWrite(2, HIGH);
  digitalWrite(3, HIGH);
  digitalWrite(4, HIGH);
  digitalWrite(5, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(10, HIGH);
  digitalWrite(12, HIGH);
  delay (delayTime);
  digitalWrite ( 12, LOW);
  delay (delayTime);
  digitalWrite ( 11, LOW);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 12, LOW);
  delay (delayTime);
  digitalWrite ( 10, LOW);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 11, LOW);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 12, LOW);
  delay (delayTime);
  digitalWrite ( 9, LOW);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 10, LOW);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 11, LOW);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 12, LOW);
  delay (delayTime);
  digitalWrite ( 8, LOW);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 9, LOW);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 10, LOW);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 11, LOW);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 12, LOW);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 8, LOW);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 9, LOW);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 10, LOW);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 11, LOW);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 12, LOW);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 8, LOW);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 9, LOW);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 10, LOW);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 11, LOW);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 12, LOW);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 6, HIGH);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 8, LOW);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 9, LOW);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 10, LOW);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 11, LOW);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 12, LOW);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 5, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 6, HIGH);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 8, LOW);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 9, LOW);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 10, LOW);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 11, LOW);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 12, LOW);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 4, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 5, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 6, HIGH);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 8, LOW);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 9, LOW);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 10, LOW);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 11, LOW);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 12, LOW);
  delay (delayTime);
  digitalWrite ( 2, LOW);
  digitalWrite ( 3, HIGH);
  delay (delayTime);
  digitalWrite ( 3, LOW);
  digitalWrite ( 4, HIGH);
  delay (delayTime);
  digitalWrite ( 4, LOW);
  digitalWrite ( 5, HIGH);
  delay (delayTime);
  digitalWrite ( 5, LOW);
  digitalWrite ( 6, HIGH);
  delay (delayTime);
  digitalWrite ( 6, LOW);
  digitalWrite ( 7, HIGH);
  delay (delayTime);
  digitalWrite ( 7, LOW);
  digitalWrite ( 8, HIGH);
  delay (delayTime);
  digitalWrite ( 8, LOW);
  digitalWrite ( 9, HIGH);
  delay (delayTime);
  digitalWrite ( 9, LOW);
  digitalWrite ( 10, HIGH);
  delay (delayTime);
  digitalWrite ( 10, LOW);
  digitalWrite ( 11, HIGH);
  delay (delayTime);
  digitalWrite ( 11, LOW);
  digitalWrite ( 12, HIGH);
  delay (delayTime);
  digitalWrite ( 12, LOW);
  delay (delayTime);}
  
void pattern16(){
 delayTime = analogRead(potPin);
 digitalWrite(2, HIGH);
 digitalWrite(4, HIGH);
 digitalWrite(6, HIGH);
 digitalWrite(8, HIGH);
 digitalWrite(10, HIGH);
 digitalWrite(12, HIGH);
 delay(delayTime);
 digitalWrite(2, LOW);
 digitalWrite(4, LOW);
 digitalWrite(6, LOW);
 digitalWrite(8, LOW);
 digitalWrite(10, LOW);
 digitalWrite(12, LOW);
 digitalWrite(3, HIGH);
 digitalWrite(5, HIGH);
 digitalWrite(7, HIGH);
 digitalWrite(9, HIGH);
 digitalWrite(11, HIGH);
 delay(delayTime);
 digitalWrite(3, LOW);
 digitalWrite(5, LOW);
 digitalWrite(7, LOW);
 digitalWrite(9, LOW);
 digitalWrite(11, LOW);
 delay(delayTime);}

void pattern17 (){
 delayTime = analogRead(potPin);
 digitalWrite(2, LOW);
 digitalWrite(3, LOW);
 digitalWrite(4, LOW);
 digitalWrite(5, LOW);
 digitalWrite(6, LOW);
 digitalWrite(7, LOW);
 digitalWrite(8, LOW);
 digitalWrite(9, LOW);
 digitalWrite(10, LOW);
 digitalWrite(12, LOW);
 t=0;}

